name:           Fautils
version:        '1.0.0'
category:       Domain Specific Language
author:         Luis Pedro Coelho and others (see AUTHORS)
maintainer:     luis@luispedro.org
github:         ngless-toolkit/ngless
license:        MIT
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - LambdaCase
  - TupleSections
other-extensions:
  - DeriveDataTypeable
  - TemplateHaskell
dependencies:
  - aeson >=0.9
  - ansi-terminal
  - async
  - atomic-write >=0.2
  - base
  - bytestring
  - bytestring-lexing
  - optparse-applicative
  - conduit >= 1.3
  - conduit-algorithms >=0.0.9.0
  - conduit-extra >=1.1.12
  - configurator
  - containers
  - convertible
  - data-default
  - deepseq >=1.3
  - directory
  - edit-distance >=0.2
  - either
  - errors >=2.1
  - extra >=1.4
  - exceptions
  - filemanip >=0.3.6
  - filepath >=1.3
  - file-embed >=0.0.8
  - gitrev
  - hashable
  - hashtables
  - hostname
  - http-conduit
  - http-client
  - IntervalMap >=0.5
  - inline-c
  - inline-c-cpp
  - mtl >=2.2
  - MissingH >=1.3
  - network
  - parsec >=3.1
  - primitive >=0.6
  - process >=1.2.3
  - regex
  - safe
  - strict
  - stm
  - stm-chans
  - stm-conduit >=2.7
  - resourcet >=1.1
  - tar >=0.5
  - template-haskell
  - text >=1.2
  - time >=1.5
  - transformers
  - tar-conduit >= 0.3.2
  - unix-compat
  - unliftio-core
  - unliftio
  - vector >=0.11
  - vector-algorithms
  - safeio
  - temporary
  - yaml

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-tabs
  - -fno-warn-missing-signatures
  - -threaded
  - -O2
  - -fno-full-laziness
  - -rtsopts
  - ! '"-with-rtsopts=-A64m -n4m -H"'

ld-options:
  - -static
  - -pthread

executables:
  RemoveFastaSeqs:
    main: RemoveFastaSeqs.hs
    other-modules:
        - Data.BioConduit
  RetrieveFastaSeqs:
    main: RetrieveFastaSeqs.hs
    other-modules:
        - Data.BioConduit
